export enum SocketEvent {
    Connection = 'Connection',
    Disconnect = 'Disconnect',
    JoinGame = 'JoinGame',
    CreateGame = 'CreateGame',
    GameCreated = 'GameCreated',
    WaitPlayer = 'WaitPlayer',
    Error = 'Error',
    Play = 'Play',
    LeaveGame = 'LeaveGame',
    Win = 'Win',
    DifferenceNotFound = 'DifferenceNotFound',
    DifferenceFound = 'DifferenceFound',
    Difference = 'Difference',
}
