export enum SocketEvent {
    Connection = 'connection',
    Disconnect = 'disconnect',
    CreateGame = 'createGame',
    GameCreated = 'gameCreated',
    Error = 'error',
    JoinGame = 'joinGame',
    WaitPlayer = 'waitPlayer',
    Play = 'play',
    LeaveGame = 'leaveGame',
    Win = 'win',
    DifferenceNotFound = 'differenceNotFound',
    DifferenceFound = 'differenceFound',
    Difference = 'difference',
    GetGamesWaiting = 'getGamesWaiting',
}
